version: '3.8'

services:

  console:
    build:
      context: .
      target: console
    image: gelateria_console
    environment:
      - DB_HOST=database
    depends_on:
      - database

  tests:
    build:
      context: .
      target: tests
    image:
      gelateria_tests

  database:
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

volumes:
  mysql:
