services:
    Doctrine\ORM\EntityManager:
        factory: [ GetWith\CoffeeMachine\Machine\Shared\Infrastructure\EntityManagers\DoctrineEntityManagerFactory, create ]
        arguments:
            - '%env(APP_ENV)%'
            - driver: '%env(DB_DRIVER)%'
              host: '%env(DB_HOST)%'
              port: '%env(DB_PORT)%'
              dbname: '%env(DB_DATABASE)%'
              user: '%env(DB_USERNAME)%'
              password: '%env(DB_PASSWORD)%'
            - !tagged dbal.type

    GetWith\CoffeeMachine\Machine\Drinks\Domain\Repositories\DrinkRepository: '@GetWith\CoffeeMachine\Machine\Drinks\Infrastructure\Repositories\DoctrineDrinkRepository'

    GetWith\CoffeeMachine\Machine\Orders\Domain\Repositories\OrderRepository: '@GetWith\CoffeeMachine\Machine\Orders\Infrastructure\Repositories\DoctrineOrderRepository'
