imports:
    - { resource: ../../../../config/machine_services.yml }

services:
    _defaults:
        autoconfigure: true
        autowire: true

    _instanceof:
        Doctrine\DBAL\Types\Type:
            tags: [ 'dbal.type' ]
        Symfony\Component\Console\Command\Command:
            tags: [ 'console.command' ]

    GetWith\CoffeeMachine\Apps\Machine\Console\:
        lazy: true
        resource: '../src'

    GetWith\CoffeeMachine\Machine\:
        lazy: true
        resource: '../../../../src/Machine/*/*/{Services,Repositories,EntityManagers,MappingTypes}'

    GetWith\CoffeeMachine\Shared\:
        lazy: true
        resource: '../../../../src/Shared/*/*/{Services,Repositories,EntityManagers,MappingTypes}'

    GetWith\CoffeeMachine\Apps\Machine\Console\Application:
        public: true
        arguments: [ !tagged console.command ]
