imports:
    - { resource: ../../../../config/shop_services.yml }

services:
    _defaults:
        autoconfigure: true
        autowire: true

    _instanceof:
        Doctrine\DBAL\Types\Type:
            tags: [ 'dbal.type' ]
        Symfony\Component\Console\Command\Command:
            tags: [ 'console.command' ]

    Gelateria\Apps\Shop\Console\:
        lazy: true
        resource: '../src'

    Gelateria\Shop\:
        lazy: true
        resource: '../../../../src/Shop/*/*/{Services,Repositories,EntityManagers,MappingTypes}'

    Gelateria\Shared\:
        lazy: true
        resource: '../../../../src/Shared/*/*/{Services,Repositories,EntityManagers,MappingTypes}'

    Gelateria\Apps\Shop\Console\Application:
        public: true
        arguments: [ !tagged console.command ]
